### ISSUE TITLE
Unknown Pod Error

### ISSUE THREAD

**Issue by nas2011** [haxall/haxall#11]
After download and unzipping, when I try to verify using the ```hx version``` command returns : 

```sys::UnknownPodErr: hx```

I've tried both executing from the haxall directory and adding \bin to PATH.
I can see in \lib\fan that the hx pod is present.
I've tried both version 3.1.3 and 3.1.4 and get the same.

Do I need to change something in the setup to look for the pod in that location? I suspect it is very simple.

Thanks in advance for the help. I am extremely new to Fantom and trying to learn as part of working with Haxall. Excited to see what the future of the project holds.

**Comment by briansfrank** [comment]
When you unzip, cd the directory above bin, lib, etc and run this:

bin/hx -version

If that throws that exception, then let us know if you are on Windows or Unix and go to the fanlaunch script and add an echo to this line to see what is actually being executed:

  exec "$FAN_JAVA" $osFlags $JAVA_OPTIONS $libPath -cp "$FAN_CLASSPATH" -Dfan.home="$FAN_HOME" "$FAN_MAIN" "$@"

Or on Windows:

%JAVA% %FAN_JAVA_OPTS% -cp %FAN_CP% "-Dfan.home=%FAN_HOME%" fanx.tools.%TOOL% %TOOL_ARGS%
