### ISSUE TITLE
ModbusBlockGap issue with Coils

### ISSUE THREAD

**Issue by rickyv1** [haxall/haxall#12]
One of our devs found the below issue while working on a customer project and it appears to be in the modbus pod which we don't have access to. The screenshots are from FIN, but this was also reproduced in the Skyspark UI v3.0.29.

How to reproduce
1. Create a new proj
2. Enable modbus ext
3. Create new registerMap called “test” like:

name,addr,data,rw,scale,dis,unit,tags
ping,00001,bit,r,,Ping,,
bit01,00001,bit,r,,,,
bit02,00002,bit,r,,,,
bit03,00003,bit,r,,,,
bit_empty,00004,bit,r,,,,
bit05,00005,bit,r,,,,
bit06,00006,bit,r,,,,
bit07,00007,bit,r,,,,

4. Create new connector with (IMPORTANT: add modbusBlockGap:3 to the default tags):

conn
modbusBlockGap:3
modbusConn
modbusRegMapUri:`data/modbus/test.csv`
modbusSlave:1
uri:`modbus-tcp://[127.0.0.1/`](http://127.0.0.1/)

5. Run a modbus slave simulator, like modsim, configured like into the attached screen, so with:

bit1 = 0
bit2 = 0
bit3 = 0
bit4 = 1 //<---- Important: set this to 1
bit5 = 0
bit6 = 0
bit7 = 0

6. Create an equip with those points referencing the registers (IMPORTANT: skip bit 4):
7. View the point live values for each
bit1 (OK: curVal should be == 0 and is == 0)
bit2 (OK: curVal should be == 0 and is == 0)
bit3 (OK: curVal should be == 0 and is == 0)
bit5 (ERROR: curVal should be == 0 and is == 1, it’s reading bit4)
bit6 (ERROR: it’s reading bit5)
bit7 (ERROR: it’s reading bit6)

Expected behavior:
You should see all the points with curVal == 0

Error
There is a shift of the value from bit 4 that is equals to 1 to bit 5 that should be equals to 0 but now it’s 1.

NOTES:
Removing modbusBlockGap:3 there is no error

Doing the same with numbers works fine, also with modbusBlockGap:3 (see pictures related to number tests)

![image-20220623-075528](https://user-images.githubusercontent.com/113636917/190506201-f802c7ac-41b2-4d81-a519-79c6b4d3c7cd.png)
![image-20220623-075958](https://user-images.githubusercontent.com/113636917/190506205-c73733bf-1261-41c8-a628-b0766681af00.png)
![image-20220623-080043](https://user-images.githubusercontent.com/113636917/190506207-9ca6c31b-2297-4fe1-83a1-5149094613ee.png)
![image-20220623-080547](https://user-images.githubusercontent.com/113636917/190506208-c8fe32fa-92a1-4d43-9bdf-53675a56f12d.png)
![image-20220623-080604](https://user-images.githubusercontent.com/113636917/190506210-3fd4aa08-c31f-4c2d-b75b-23eb9d618977.png)
![image-20220623-081021](https://user-images.githubusercontent.com/113636917/190506212-4f28e049-e876-4080-912a-48d8f6b3a2a7.png)

**Comment by mgiannini** [comment]
@rickyv1 thanks for reporting this bug. I was able to reproduce and have pushed a fix. note - this fix is only for SkySpark versions that support the Haxall connector framework, so it will not work in FINStack or SkySpark `3.0.29`

**Comment by rickyv1** [comment]
Thank you, Matthew! I understand it is for the newer SkySpark versions.
________________________________
