### ISSUE TITLE
NullErr when calling ConnDispatch.close()

### ISSUE THREAD

**Issue by SlimerDude** [haxall/haxall#14]
https://github.com/haxall/haxall/blob/216df9374975d263cf38d397455304a59ee92e91/src/lib/hxConn/fan/ConnDispatch.fan#L98

`ConnDispatch.close(Err? cause)` has a nullable `cause`, but the underlying `ConnMgr.close(Obj cause)` does not allow nulls.

So, err, passing `null` to `ConnDispatch.close()` results in a `NullErr`.

**Comment by briansfrank** [comment]
Matthew fix this this month:

https://github.com/haxall/haxall/commit/c33649f28fe0447ba43439e9bc1f0db89d6952c3

**Comment by briansfrank** [comment]
Fixed
