### ISSUE TITLE
Clarifications on the Build process

### ISSUE THREAD

**Issue by NeedleInAJayStack** [haxall/haxall#16]
I'm trying to dockerize to this repo so that it's really easy to get a new Haxall instance up and running. There are 2 options:

1. Make a Dockerfile that downloads the pre-bundled zip from the GitHub release and sets it up
2. Make a Dockerfile in this repo that performs the build process

I have done option 1 [here](https://github.com/NeedleInAJayStack/haxall-docker), and it works fine. The big downside is that I must manually run the docker build/publish process on any newly released versions.

Option 2 is ideal, as it could be integrated into this repo's CI, and published to this repo's container registry automatically. I have an attempt in [this commit](https://github.com/NeedleInAJayStack/haxall/commit/e9d0b6f1eec5a619e13d8239fe79a394efc4dde6) on [this branch](https://github.com/NeedleInAJayStack/haxall/tree/feature/dockerfile) that tried to follow the [Build documentation](https://haxall.io/doc/docHaxall/Build). However, I ran into the following issues:

- Overlapping files are created by the `fantom`, `haystack-defs`, and `haxall` build processes (specifically, `.props` and `.pod` files). It wasn't always clear whether the Haxall release zip had combined these, and if so which ones took precedence.
- ~~The web UI tables aren't able to render correctly. The browser console gave the following error `Uncaught: Object { "$err": Error, m_msg: "FontMetrics not supported: 700 9pt Helvetica", m_cause: undefined }`.~~

Could you provide guidance on the process used to generate the release zips?

**Comment by NeedleInAJayStack** [comment]
> The web UI tables aren't able to render correctly. The browser console gave the following error `Uncaught: Object { "$err": Error, m_msg: "FontMetrics not supported: 700 9pt Helvetica", m_cause: undefined }

Figured this out - it was a consequence of using an incompatible SWT.

**Comment by mgiannini** [comment]
Taking a look at your Dockerfile now and trying to reproduce. Then I should be able to give some guidance...

**Comment by NeedleInAJayStack** [comment]
Hey @mgiannini! Mostly I was a little concerned that the final `haxall` directory didn't look the same between my Docker image and the release zip, and was hoping to get more details on the process followed to create the zip.

For example:

- Files the zip release includes, that the docker image doesn't:
    - lib/fan/arcbeam.pod
    - lib/fan/hxClone.pod
    - lib/fan/hxCluster.pod
- Files the docker image includes but the zip release does not
    - bin/nstub.exe
    - etc/syntax/*
    - sys/tz.js
    - lib/fan/icons.pod
    - lib/fan/webfwt.pod
    - lib/fan/webmod.pod
    - lib/fan/doc*.pod
    - lib/fan/test*.pod
    - A bunch of flux artifacts

Note: Some of these may be due to changes since the 3.1.7 release

**Comment by mgiannini** [comment]
We have a pretty custom build process for generating the final haxall.zip.  The code for those 3 pods is not part of haxall, so we have to "inject" them into the final zip. So you will probably need something in your Dockerfile that downloads the zip and extracts those 3 pods and copies them into lib/fan/.

The other things you will need to custom remove as part of your dockerfile.  It's probably not strictly necessary to remove them, but if you want the Docker image to exactly match the haxall zip you'll need to do some custom pruning.

**Comment by NeedleInAJayStack** [comment]
Oh gotcha. Ok, if Haxall alone isn't able to generate the zip release, then I think just downloading the zip directly and configuring it (option 1 in my first message) is best, as opposed to trying to build it. Thanks for the information @mgiannini!
