### ISSUE TITLE
unable to run mqtt function

### ISSUE THREAD

**Issue by mveea** [haxall/haxall#17]
Hi 👋
I was trying to run the mqtt example provided in the official documentation:
https://haxall.io/doc/lib-mqtt/doc

I have created an mqttConn using the WebUI
> id:@2c02857d-b9358a39 "MQTT Connector"
> dis:MQTT Connector
> conn
> mod:2023-05-25T20:45:49.028Z
> mqttClientId:MqttTestClient
> mqttConn
> mqttVersion:"v3.1.1"
> uri:"mqtt://broker.hivemq.com/"

but when I run the mqtt publish function, in the haxall shell
`read(mqttConn).mqttPublish("testTopic", "Hello, MQTT!", {mqttQos: 2})`
I get the following error:
`☹axon::EvalErr: Unknown symbol 'mqttPublish' [eval:1]
axon::EvalErr: Unknown symbol 'mqttPublish' [eval:1]
  axon::AxonContext.resolve (AxonContext.fan:197)
  axon::Var.eval (Var.fan:23)
  axon::Expr.evalToFunc (Expr.fan:62)
  axon::Call.evalTarget (Call.fan:42)
  axon::Call.eval (Call.fan:39)
  hxd::HxdContext.evalOrReadAll (HxdContext.fan:165)
  hx::HxEvalOp.onRequest (HxApiOp.fan:193)
  hx::HxApiOp.onService (HxApiOp.fan:41)
  hxApi::HxApiWeb.onService (HxApiWeb.fan:52)
  hxHttp::HttpRootMod.onService (HttpRootMod.fan:54)
  wisp::WispActor.process (WispActor.fan:80)
  wisp::WispActor.receive (WispActor.fan:38)
  concurrent::Actor._dispatch (Actor.java:274)
  concurrent::Actor._work (Actor.java:229)
  concurrent::ThreadPool$Worker.run (ThreadPool.java:273)`

Does something specific needs to be done to pods to enable functions?

**Comment by mveea** [comment]
as complementary information, it seems that the library _conn_ isn't loaded at start

> [09:15:06 30-May-23] [info] [init] Create projMeta
> [09:15:07 30-May-23] [info] [init] Create lib [ph]
> [09:15:07 30-May-23] [info] [init] Create lib [phScience]
> [09:15:07 30-May-23] [info] [init] Create lib [phIoT]
> [09:15:07 30-May-23] [info] [init] Create lib [phIct]
> [09:15:07 30-May-23] [info] [init] Create lib [hx]
> [09:15:07 30-May-23] [info] [init] Create lib [obs]
> [09:15:07 30-May-23] [info] [init] Create lib [axon]
> [09:15:07 30-May-23] [info] [init] Create lib [crypto]
> [09:15:07 30-May-23] [info] [init] Create lib [http]
> [09:15:07 30-May-23] [info] [init] Create lib [hxApi]
> [09:15:07 30-May-23] [info] [init] Create lib [hxShell]
> [09:15:07 30-May-23] [info] [init] Create lib [hxUser]
> [09:15:07 30-May-23] [info] [init] Create lib [io]
> [09:15:07 30-May-23] [info] [init] Create lib [task]
> [09:15:07 30-May-23] [info] [init] Create lib [point]
> [09:15:09 30-May-23] [info] [init] Update httpPort [8080]
> [09:15:09 30-May-23] [info] [init] Create su ["hello"]

**Comment by briansfrank** [comment]
You will have to enable both the conn and mqtt libs first.  You can see what libs are enabled via the libs() function.

To enable call these two functions in your shell:

libAdd("conn")
libAdd("mqtt")
