### ISSUE TITLE
Setup issues

### ISSUE THREAD

**Issue by flintsaw** [haxall/haxall#26]
Fresh git clone of the main branch on debian 12.

The documentation calls for bin/fanlaunch which doesn't exist.
![image](https://github.com/haxall/haxall/assets/76706713/86c8f9d1-af59-422b-9415-55d697cbbe8c)

As a hacky solution I copied bin/fanlaunch from 3.1.9 and it seemed to work.

I then attempted to run ./hx and got the following error.
![image](https://github.com/haxall/haxall/assets/76706713/4f952940-9bed-4ad5-ad08-46eacff744a1)

Where is this file located?

I had been playing with 3.1.9 but it does not have a /src file. Since 3.1.9 is working I copied over /src but this is janky.

Thanks for the help!

**Comment by briansfrank** [comment]
Its not clear if you are trying to build from source or using the zip file.  If you just downloaded the zip, then everything is packaged up for you and you should have bin/hx and bin/fanlaunch.

But if you are building from source, then its a lot more setup covered here:

https://haxall.io/doc/docHaxall/Build

And we are in the process of adding Xeto repo to the dependencies (but I haven't updated the docs yet until we do build 3.1.10)

**Comment by briansfrank** [comment]
Use the Build docs that are checked into the repo here:

https://github.com/haxall/haxall/blob/main/src/doc/docHaxall/doc/Build.fandoc

**Comment by flintsaw** [comment]
Thanks Brian, that did it!
