### ISSUE TITLE
Trouble Building Haxall

### ISSUE THREAD

**Issue by gtfierro** [haxall/haxall#3]
I'm in the process of putting together a Dockerfile for Haxall and I'm running into trouble building it. I'm using the latest fantom release (1.0.76), latest haystack-defs main branch and the latest haxall main branch. 

Following the directions on the README, the build seems to work fine until it fails on an `Unknown method 'web::WebOutStream.initJs'`.

Full trace below:

```
root@f4ae8ab5a88f:/haxall# src/build.fan
compile [rdf]
  Compile [rdf]
    FindSourceFiles [9 files]
    CompileJs
    WritePod [file:/haxall/lib/fan/rdf.pod]
compile [haystack]
  Compile [haystack]
    FindSourceFiles [50 files]
    CompileJs
    WritePod [file:/haxall/lib/fan/haystack.pod]
compile [auth]
  Compile [auth]
    FindSourceFiles [13 files]
    CompileJs
    WritePod [file:/haxall/lib/fan/auth.pod]
compile [def]
  Compile [def]
    FindSourceFiles [18 files]
    CompileJs
    WritePod [file:/haxall/lib/fan/def.pod]
compile [defc]
  Compile [defc]
    FindSourceFiles [45 files]
    WritePod [file:/haxall/lib/fan/defc.pod]
compile [axon]
  Compile [axon]
    FindSourceFiles [39 files]
    CompileJs
    WritePod [file:/haxall/lib/fan/axon.pod]
compile [obs]
  Compile [obs]
    FindSourceFiles [7 files]
    WritePod [file:/haxall/lib/fan/obs.pod]
compile [folio]
  Compile [folio]
    FindSourceFiles [14 files]
    CompileJs
    WritePod [file:/haxall/lib/fan/folio.pod]
compile [hx]
  Compile [hx]
    FindSourceFiles [12 files]
    CompileJs
    WritePod [file:/haxall/lib/fan/hx.pod]
compile [hxStore]
  Compile [hxStore]
    FindSourceFiles [9 files]
    WritePod [file:/haxall/lib/fan/hxStore.pod]
  javaNative [hxStore]
    Exec [/docker-java-home/bin/java -cp /fantom/lib/java/sys.jar -Dfan.home=/fantom fanx.tools.Jstub -d /haxall/src/core/hxStore/temp-java hxStore]
    Java Stub [hxStore]
    CompileJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
    Exec [/docker-java-home/bin/jar -xf /haxall/src/core/hxStore/temp-java/hxStore.jar]
    Delete [file:/haxall/src/core/hxStore/temp-java/hxStore.jar]
    Delete [file:/haxall/src/core/hxStore/temp-java/meta-inf/]
    Exec [/docker-java-home/bin/jar -fu /haxall/lib/fan/hxStore.pod -C /haxall/src/core/hxStore/temp-java .]
    Delete [file:/haxall/src/core/hxStore/temp-java/]
compile [hxFolio]
  Compile [hxFolio]
    FindSourceFiles [19 files]
    WritePod [file:/haxall/lib/fan/hxFolio.pod]
compile [hxd]
  Compile [hxd]
    FindSourceFiles [11 files]
    WritePod [file:/haxall/lib/fan/hxd.pod]
compile [hxApi]
  Compile [hxApi]
    FindSourceFiles [2 files]
    WritePod [file:/haxall/lib/fan/hxApi.pod]
compile [hxHttp]
  Compile [hxHttp]
    FindSourceFiles [1 files]
    WritePod [file:/haxall/lib/fan/hxHttp.pod]
compile [hxUser]
  Compile [hxUser]
    FindSourceFiles [7 files]
    WritePod [file:/haxall/lib/fan/hxUser.pod]
compile [hxShell]
  Compile [hxShell]
    FindSourceFiles [12 files]
/haxall/src/lib/hxShell/fan/HxShellWeb.fan(63,7): Unknown method 'web::WebOutStream.initJs'
BUILD FAILED [7739ms]!
```

The Dockerfile (and the shell script that starts it) are available [here](https://gist.github.com/gtfierro/3c655904100d6abbb3af300127ba8e82) so you can see what I'm doing. I tried building with the latest master branch of `fantom`, but then running `fan` results in:

```
 > [11/15] RUN /haystack-defs/src/build.fan:
#14 0.383 Error: Could not find or load main class fanx.tools.Fan
#14 0.383 Caused by: java.lang.ClassNotFoundException: fanx.tools.Fan
```

I also tried to build on my Ubuntu machine and hit the same issues, so I don't think its a question of the Docker image not having some dependency.

Let me know if I'm missing anything or if I can provide any more info

**Comment by mgiannini** [comment]
Hi Gabe - if you are going to be building Haxall from the "tip" of the development branch, you will need to compile against the source for Fantom.  This issues is discussed in more detail in this [ticket](https://github.com/haxall/haxall/issues/2)

**Comment by gtfierro** [comment]
I'll try the bootstrap instructions, thanks!

Is there a way to avoid compiling Fantom from source? The way you phrased your response makes it sound like if I'm not building Haxall from tip, then there's an easier way?

**Comment by gtfierro** [comment]
I'm having trouble running the bootstrap script:

```
 > [ 7/17] RUN cd /fantom && ./bin/fan adm/bootstrap.fan:
#10 1.126 [16:00:15 15-Jul-21] [err] [bootstrap] Cannot boot
#10 1.127 sys::NullErr: Coerce to non-null
#10 1.127   fan.sys.NullErr.makeCoerce (NullErr.java:38)
#10 1.127   bootstrap_0::Bootstrap.execToStr (/fantom/adm/bootstrap.fan:243)
#10 1.127   bootstrap_0::Bootstrap.initEnv (/fantom/adm/bootstrap.fan:78)
#10 1.127   bootstrap_0::Bootstrap.run (/fantom/adm/bootstrap.fan:56)
#10 1.127   util::AbstractMain.main (AbstractMain.fan:373)
#10 1.127   jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (NativeMethodAccessorImpl.java)
#10 1.127   jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
#10 1.127   jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
#10 1.127   java.lang.reflect.Method.invoke (Method.java:564)
#10 1.127   fan.sys.Method.invoke (Method.java:573)
#10 1.127   fan.sys.Method$MethodFunc.callOn (Method.java:244)
#10 1.127   fan.sys.Method.callOn (Method.java:139)
#10 1.127   fanx.tools.Fan.callMain (Fan.java:185)
#10 1.127   fanx.tools.Fan.executeFile (Fan.java:105)
#10 1.127   fanx.tools.Fan.execute (Fan.java:37)
#10 1.127   fanx.tools.Fan.run (Fan.java:308)
#10 1.127   fanx.tools.Fan.main (Fan.java:346)
```

Do I need to have both the `rel` and `dev` folders set up manually, or does the bootstrap script intend to handle that?

**Comment by mgiannini** [comment]
Gabe - we reverted the change in Haxall that is causing this compile issue.  So you shouldn't need to build Fantom from source anymore..

As a side note the bootstrap.fan script requires user input (confirmation). If you want to continue with trying to build Fantom from source, I'd recommend doing it locally (outside of a Docker container) so you can see all the steps. Then try to script it up in Docker.

**Comment by gtfierro** [comment]
Thanks for that! I'd be happy to download a specific Haxall release rather than building from tip, if that's something you'd consider supporting going forward.

I'm able to successfully build and run Haxall now. The Dockerfile + supporting scripts are available [here](https://gist.github.com/gtfierro/3c655904100d6abbb3af300127ba8e82); let me know if that's something you'd like me to submit as a PR. Could be an easier point of entry

**Comment by briansfrank** [comment]
Hi Gabe,

We just started Haxall, so there is no documentation nor official releases yet.  First real release will probably be in Sept and then it will be available as just a zip file you can install and use with a Java VM.  In meantime, if you just want a pre-build zip you can grab one from link below (building from source requires a few steps):

https://www.dropbox.com/s/1s8l7hoiph7sbs9/haxall-3.0.29.zip?dl=0

Not sure what you are doing and there are no docs yet.  Most likely you want the defc program which you can run with "bin/fan defc -?".  There is also a program to convert b/w all the files (Trio to JSON for example) using "hx convert".  Otherwise shoot me an email and happy to help.

**Comment by gtfierro** [comment]
Ok, I will keep an eye out!

I'm just looking for a way to see how I can query Haystack 4 definitions and models. I was hoping this would be possible through Haxall as it is hard to tell which of the tools at https://project-haystack.org/download support Haystack 4. I also had some trouble finding documentation on the query language (Axon?); I know some basic queries but wasn't sure where to look for the kinds of operators that are now supported in v4
