### ISSUE TITLE
Clarification on Folio Storage and Haxall Use Case

### ISSUE THREAD

**Issue by ThomasMagnum308** [haxall/haxall#33]
Just wanted to get some clarification on the way the folio database stores data and the capabilities of Haxall.

“Folio persists data to disk, but operates as an in-memory based database. Records are read from disk on startup and stored in RAM for fast access. This design supports the real-time nature of sensor data. But it also imposes limits on Folio since most hardware tend to have less RAM than disk space.”

I’m attempting to pull history data and points from multiple JACEs (100+) via nHaystack. Each of these JACEs has multiple pieces of equipment with 20+ points each.

I want to leverage the compression and query speed of Folio to create a single API endpoint for exporting data for visualizations.

Is this a valid use case for Haxall given a sufficiently capable server?
Do I need to store the historical data elsewhere?

Thank you for the info.

**Comment by briansfrank** [comment]
The Haxall version of Folio does not contain a historian database.  So its not optimized to work with history data.  What Haxall does provide is a RAM buffer to store history data in memory as a staging point between south bound devices (like Niagara) and an north bound systems (SkySpark, cloud, real database, etc).  The intention is that Haxall is just the gateway, not the database you use to build visualization applications
