### ISSUE TITLE
Haxall as Haystack server

### ISSUE THREAD

**Issue by jaroli** [haxall/haxall#4]
I managed to install Haxall on Ubuntu 18 and I am able to start the hx daemon and the Axon shell UI.
Not sure about the scope of Haxall or what to do next :)

I am mostly interested in using it as a Haystack server. 
Is this possible? How do I send requests to the API?

**Comment by ZTSAdam** [comment]
You can set up a web server with a custom API using the [wisp ](https://fantom.org/doc/wisp/index) and [webMod](https://fantom.org/doc/webmod/index) Fantom libraries. There doesn't appear to be a built in web serve within Haxallr, but it should be quick to set one up for some basic services.

**Comment by abible-intellastar** [comment]
Take a look at the [wisp](https://fantom.org/doc/wisp/index) and [wedmod](https://fantom.org/doc/webmod/index) fantom libraries, you can spin up a server with a basic web service pretty quickly. I don't believe Haxall has a native web server.

**Comment by jaroli** [comment]
According to this post https://skyfoundry.com/forum/topic/5924
the Haxall Daemon has a webserver with full support for the Haystack HTTP API.

But this gives the 404 error:
```
http://localhost:8080/api/demo/about
```

**Comment by abible-intellastar** [comment]
Hrm, I missed that on my first skim-through.

I would check to see if you have a project named "demo", it might be named something else unless you created it.

**Comment by mgiannini** [comment]
@jaroli - Haxall only supports a single project, so you issue API requests directly to `/api/`

```text
http://localhost:8080/api/about
```

**Comment by abible-intellastar** [comment]
Good to know, thanks Matthew!

**Comment by jaroli** [comment]
Confirming that API works, for example:
```
localhost:8080/api/read?filter=point
```
Thank you!
