### ISSUE TITLE
Main branch build fails - Unknown method 'sys::Int.clamp'

### ISSUE THREAD

**Issue by jwhittier99** [haxall/haxall#8]
Building the main branch from the updates yesterday fail with the unknown method below. Branch 3.1.2 builds successfully. 

/Users/myUser/Documents/haxall/src/lib/hxConn/fan/ConnLib.fan(215,35): Unknown method 'sys::Int.clamp'
/Users/myUser/Documents/haxall/src/lib/hxConn/fan/ConnLib.fan(216,23): Unknown method 'sys::Int.clamp'
BUILD FAILED [5816ms]!

**Comment by mgiannini** [comment]
In order to build the development branch of Haxall, you also need to be using the development branch of the Fantom repository. That is a new method on Int in Fantom.
